config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user
  validates_presence_of :date, :rationale
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name
  has_many :posts

  def full_name
    last_name.upcase + ', ' + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      return if Admin.admin_types.include?(current_user.try(:type))

      flash[:alert] = 'You are not authorized to access this page'
      redirect_to(root_path)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show update edit destroy]

  def index
    if current_user.try(:type) == 'AdminUser'
      @posts = Post.all
    else
      @posts = current_user.posts
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to posts_path, notice: 'Your post was created successfully'
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to post_path, notice: 'Your post was updated successfully'
    else
      render :edit
    end
  end

  def show; end

  def destroy
    return unless @post.destroy

    redirect_to posts_path, notice: 'Your post was deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale, :status)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(path)
    'active' if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav'%>
          <%= render 'shared/main'%>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>

  <%= render 'shared/errors', obj: @post %>

  <div class="custom-form">

    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date, class: 'date-field form-control', id: 'date' %>
    </div>

    <div class="form-group">
      <%= f.label :rationale %>
      <%= f.text_area :rationale, class: 'form-control', id: 'rationale' %>
    </div>

    <%= render partial: 'status', locals: { f: f } if current_user.type == 'AdminUser' %>

    <%= f.submit "Submit", class: 'btn btn-primary' %>

  </div>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <tr>
    <td>
      <%= post.id %>
    </td>
    <td>
      <%= post.date %>
    </td>
    <td>
      <%= post.user.full_name %>
    </td>
    <td>
      <%= truncate(post.rationale) %>
    </td>
    <td>
      <%= link_to 'Edit', edit_post_path(post.id), id: 'edit', class: 'btn-sm btn-secondary text-decoration-none' %>
    </td>
    <td>
      <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure you would like to delete #{post.user.full_name}" }, :class => "no-link"  do %>
        <%= image_tag asset_pack_path('media/images/icon-delete.svg') %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'approved' %>
  <%= f.label :status, 'Approved' %>

  <%= f.radio_button :status, 'rejected' %>
  <%= f.label :status, 'Rejected' %>
</div>

app/views/posts/edit.html.erb
<h1 class="mt-3">Edit Post</h1>

<%= render 'form', collection: @posts %>

app/views/posts/index.html.erb
<h1 class="mt-3">Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>
        Date
      </th>
      <th>
        User
      </th>
      <th>
        Rationale
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render 'posts', collection: @posts %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1 class="mt-3">New Post</h1>

<%= form_for @post do |f| %>
  <div class="custom-form form-group">

    <%= f.label :date %><br>
    <%= f.date_field :date, class: 'date-field form-control' %><br>

    <%= f.label :rationale %><br>
    <%= f.text_area :rationale, class: 'form-control' %><br>

    <%= f.submit "Submit", class: 'btn btn-primary' %>

  </div>
<% end %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container m-4">
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-danger">
            <h2><%= pluralize(obj.errors.count, "error") %>
            prohibited your <%= obj.class.name %> from being created</h2>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_main.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %> m-4">
        <%= message %>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1 class="mt-3">Time Tracker</h1>
</div>

<% if current_user %>
  <ul class="custom-nav nav nav-tabs">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link #{active?(root_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "Time Entries", posts_path, class: "nav-link #{active?(posts_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "New Entry", new_post_path, class: "nav-link #{active?(new_post_path)}", id: 'new-entry' %>
    </li>
    <li class="nav-item dropdown ml-md-auto">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Options</a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

        <% if current_user.try(:type) == "AdminUser" %>
          <%= link_to "Admin Dashboard", admin_root_path, class: 'dropdown-item' %>
          <div class="dropdown-divider" ></div>
        <% end %>

        <div>
          <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: 'dropdown-item' %>
        </div>
      </div>
    </li>
  </ul>
<% end %>